[build]
  command = "npm run build"
  publish = "build"

# This handles the page refresh issue by redirecting all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force HTTPS for all requests
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "upgrade-insecure-requests"